content/installs/cpe2/index.md

- Added intro
- Reindented lines and added spacing for structural clarity

CPE 2 instructions tweaks

---

courtesy.md

First draft of courtesy guidelines for installers.
Based on my own experience doing site work for an engineering firm + first nymesh install.
Will add link on Install webpage after feedback from other install team members.

Adding draft install courtesy guidelines document

---

content/organization/workflow.md

Fix broken link to map. I ran it locally and the link worked.

Update map link

---

content/installs/safety.md

Added travel safety note after install team member was robbed en route to install  :(

Added travel safety note

---

content/installs/_index.md
content/installs/equipment.md
content/installs/kit.md

From https://nycmesh.slack.com/messages/G0FS2EVSQ/p1522292807000071

Add install kit

---

content/hardware/nsm5.md
content/installs/nsm5.md
content/software/nsm5-flash.md

Add affiliate code to Amazon links

Affiliate Links

---

content/installs/equipment.md

Fix affiliate links

---

content/security/_index.md

Add security page

---

layouts/_default/baseof.html
layouts/_default/single.html
layouts/partials/sidebar.html

@olivernyc What do you think of this change? Gets rid of a silly bar on the left and a feels a bit more open.

Slightly more compact layout

---

content/hardware/tplink.md

Small edit to the TP-Link configuration doc

TP-Link configuration doc 

---

content/hardware/config.md

added a link to TP-Link config doc

added a link to config doc

---

content/hardware/config.md

Added the configuration for a SXT Kiosk + VPN to NYC Mesh

added kiosk vpn config

---

content/installs/Crimping.md

Added the link to the 2nd Crimping Video to the page.

added 2nd Crimping Video

---

content/intro/typical Installs.md

Minor language and grammar edits.

Update typical Installs.md

---

content/installs/equipment.md

Removed switch router, edited some language, edited google doc

Small edits

---

content/intro/typical Installs.md

Fixing a couple of typos as I read through this great page.

Just fixing a couple of typos

---

content/hardware/mikrotikspecifics.md

Changed "under" to "understand". I'm pretty sure this is a typo.

Added clairity

---

content/networking/vpn.md
content/networking/vpnl2tpipsec.md
content/networking/vpnwireguard.md
netlify.toml

This pull request coalesces my work on the VPN portion of the NYC Mesh documentation. My goals for this chunk of work are:
* Improve beginner-level comprehension regarding the purpose of the NYC Mesh VPN service.
* Clarify existing instructions for end-user connection and setup procedures.
* Expand existing documentation to cover additional device/OS combinations.
* Add visuals such as example screenshots.
* Offer suggestions for improved formatting (using Hugo features such as relative links) and general readability (e.g., more "scannable" text with Markdown-formatted lists, headers, etc).
Please feel free to merge this PR at whatever point is comfortable as it will not include any code changes beyond content-level links and formatting. I.e., no CSS/templating changes will be commited to …

Improvements to VPN documentation.

---

content/_index.md

This is a pull request

---

content/_index.md

Cleanup demo commits

---

content/software/mikrotikfirmware.md

This is mostly to start a discussion. I am testing on a microtik. I was mostly confused by the different versions linked.

Bump versions of firmware to latest stable 6.46.1

---

content/intro/typical Installs.md

just wanted to clean up some spelling, add missing words :)

fixing a few typos

---

content/hardware/config.md

add liteap configuration

---

content/networking/ntp.md

added NTP Page

---

content/hardware/config.md

First commit is editor linting, but the second commit is where it counts.

Slight rewording on config.md

---

content/intro/typical Installs.md

Fixes a few links and formatting issues in the Typical Installations page.

Fix a few formatting issues on typical installations page

---

content/diy/_index.md
content/hardware/config.md
content/installs/nn.md

Text update regarding the recycling of uninstalled "node number" and changed in naming. 
Install Number (or Install Request Number and no more node number) and the introduction of Network Number or NN

Network number

---

content/networking/hubs.md

These edits to the Hubs page came from suggestions and comments in [this Google Doc](https://docs.google.com/document/d/1tuDJhUL5pvqJW9f1ZL1TQI3_wRLWhKr2gD3WGudmi70/edit?ts=60396139). I didn't have a chance to incorporate them before the initial PR (#126) was merged.

Revisions to Hubs page

---

content/networking/vpnl2tpipsec.md

This is necessary for using OSPF over the L2TP VPN.

Add workaround for incorrect MTU for L2TP VPN using EdgeRouter

---

content/hardware/tplink.md

update router models in docs

---

content/hardware/config.md

Pictures and animations coming soon!

Add WinBox config tutorial to Configs page

---

content/networking/vpnl2tpipsec.md

Added a link to request account

added a link to cred page

---

content/hardware/config.md
content/hardware/litebeamac.md

Added how to configure a LiteBeam via SSH and revised instructions for standard configuration.
**Configs page**
- Configgen for LiteBeam LR
- Network Number inline form
- Walk-through uploading config file
- Merge LR with LBE config method
**LBE page**
- Changing LBE config using SSH
- Doing a scan via SSH

LiteBeam SSH and new config

---

content/organization/protecting.md

Incorporated feedback from more sources and fixed some typos and language!

Final draft of the Protecting the Mesh document

---

content/hardware/config.md

Once https://github.com/nycmeshnet/nycmesh-configs/pull/20 is merged, the SXT configs from configgen will no longer have this bug

Simplify SXTsq config instructions

---

content/firmware/mikrotik_netinstall_recovery.md

I documented the recovery procedure with `netinstall` for a broken OmniTIK. Hopefully it is useful to future tinkerers!

add mikrotik netinstall recovery procedure to Firmware section

---

content/networking/vpnl2tpipsec.md

Both are issues I ran into setting this up today.

Add notes on account limit, reboot maybe needed

---

content/installs/fiber splicing.md

@bhny I noticed the end of JohnB's Fiber Splicing article got cut off, so I added it at the end.

Add missing content (likely cutoff by Slack)

---

content/organization/documents
content/organization/documents.md

Added new page to Organization tab with embed to Google Drive public folder.

Add public facing documents to doc page

---

netlify.toml

Redirect /networking/* (all pages) to the wiki Networking book. Lets see if this works...
Need to create pull request to test on netlify deploy. **DON'T MERGE YET!!**

Add redirects to Wiki Pages. (Wait for #website slack confirmation to merge)

---

netlify.toml

Redirect to nycmesh.net/query instead

Update Query Redirect
